feat:로그아웃, 회원가입뷰 이름 InputType지정
TEAMSTORMERS/STORM_Android pull request #159
Opened 2020-08-19 20:45 UTC by SONPYEONGHWA

로그아웃도 똑같이 인덱스랑 자동로그인 해제하면 되겠지??

2020-08-19 20:49 UTC, SEONGGYU96 requested changes
하나만!

2020-08-19 20:49 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/fragment/MypageProfileFragment.kt
>              )
필요한 값은 다 지웠는데 스택에서 모든 액비비티를 제거하고 로그인 화면으로 넘어가야할듯! 뒤로 버튼 누르면 다시 마이페이지 오겠따 ㅋㅋ

2020-08-19 20:50 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/mypage/fragment/MypageProfileFragment.kt
>              )
아맞다!!!! 오케오케

2020-08-19 20:56 UTC, SEONGGYU96 approved these changes
좋 습니다 ! 고생많았으 ㅠㅠ

2020-08-19 20:57 UTC, merged

2020-08-20 03:56 UTC, ymcho24 reviewed
이미 머지됐지만 저도 확인했슴다!!! 로그인 회원가입 로그아웃까지 끝장났내...👍👍