Feature/refactor mypage
TEAMSTORMERS/STORM_Android pull request #250
Opened 2021-06-11 09:55 UTC by SONPYEONGHWA

1️⃣ MyPageFragment를 만들어서 SingleActivity의 navigation에 넣어주었습니다.

2️⃣ MyPage의 메인, 회원탈퇴 하위 여러뷰에서 background가 공통적으로 적용되어 layout을 따로 작성한 후 include 형식으로 만들었는데 적절한지 궁금합니다.

3️⃣ MyPageViewModel에서 다른 user data를 받아와서 LiveData에 넣어주었는데 userName은 Two way Binding을 사용해야해서 일단 name속성만 따로 만들어주었는데 다른 좋은 방법이 있을까요?
userData에서 name을 뽑으면 타입이 LiveData<String>이 아니라서 일단 이렇게 해두었습니다.

4️⃣ 기존에 만들어져있던 RoundEditText를 사용하려다 MyPage에 맞는 커스텀이 아직 아닌것 같아 일단 그냥 EditText로 만들었습니다. 그렇기 때문에 BindingAdapter를 새로 만들어주었습니다. CustomEditText의 네이밍을 조금 수정하고 My Page의 EditText의 기능을 추가할까요?? 충돌의 여지가 있어 아직 안건드렸습니다.

5️⃣ 또한 errorBody를 파싱해서 만약 서버통신에 에러가 있을 때 Toast Message로 띄워주었습니다. errorBody 파싱하는 과정을 NetworkExtension에 추가하는건 어떤가요!
![KakaoTalk_20210611_175805137](https://user-images.githubusercontent.com/56873136/121668617-6f170300-cae6-11eb-9f82-101c776313c1.png)

에러사항을 처리하기 위해 _isSuccessFetchData를 MutableLiveData<Map<Boolean, String>>으로 만들어 주었습니다. 
![image](https://user-images.githubusercontent.com/56873136/121666486-45f57300-cae4-11eb-914a-85f0153a66ba.png)

**<MyPageFragment.kt>**  

    private fun setUserData() {  
        viewModel.isSuccessFetchData.observe(viewLifecycleOwner) { isSuccessed ->  
      if(isSuccessed[true].isNullOrEmpty()) {  
                Toast.makeText(requireContext(), "유저정보를 불러올 수 없습니다.", Toast.LENGTH_SHORT).show()  
            }  
        }  
    }

5️⃣기존에 cardview로 모서리를 깎거나 동적으로 oval shape을 적용해주었었는데, Material Theme의 ShapeableImageView를 이용하면 간단하게 radius 값을 조정할 수 있습니다. 이 방법이 추천되지 않는 방법이라면 다른 방법으로 바꿔보겠슴둥

      <com.google.android.material.imageview.ShapeableImageView  
	      android:id="@+id/imageview_profile"  
	      android:layout_width="0dp"  
          android:layout_height="0dp"  
	      app:layout_constraintDimensionRatio="1:1"  
	      app:layout_constraintEnd_toEndOf="parent"  
	      app:layout_constraintWidth_percent="0.5"  
	      app:layout_constraintVertical_bias="0.0"  
	      loadImageUrl="@{viewModel.userData.userImage}"  
	      android:background="@drawable/ic_launcher_background"  
	      app:shapeAppearance="@style/ShapeAppearance.App.CircleImageView"  
	      app:layout_constraintStart_toStartOf="parent"  
	      app:layout_constraintBottom_toBottomOf="parent"  
	      app:layout_constraintTop_toTopOf="@id/guideline" />

![image](https://user-images.githubusercontent.com/56873136/121662291-1f353d80-cae0-11eb-9209-96c5be17c4b3.png)

- style속성으로 radius를 조정할 수도 있고 dimen속성과 BindingAdapter를 이용하여 유연하게 설정할 수도 있습니다!

**<예시>**

**Binding Adapter**

    @BindingAdapter("setCircleOutline")  
    @JvmStatic  
    fun ShapeableImageView.setCircleOutline(radius: Float) {  
        shapeAppearanceModel = ShapeAppearanceModel().withCornerSize(radius)  
    }

**dimens.xml**
![image](https://user-images.githubusercontent.com/56873136/121664756-c915c980-cae2-11eb-8dca-eb06772f33e1.png)

**ShapeableImageView**

    <com.google.android.material.imageview.ShapeableImageView  
      android:id="@+id/imageview_profile"  
      android:layout_width="0dp"  
      android:layout_height="0dp"  
      app:layout_constraintDimensionRatio="1:1"  
      app:layout_constraintEnd_toEndOf="parent"  
      app:layout_constraintWidth_percent="0.5"  
      app:layout_constraintVertical_bias="0.0"  
      setCircleOutline="@{@dimen/radius_circle}"  
      loadImageUrl="@{viewModel.userData.userImage}"  
      android:background="@drawable/ic_launcher_background"  
      app:layout_constraintStart_toStartOf="parent"  
      app:layout_constraintBottom_toBottomOf="parent"  
      app:layout_constraintTop_toTopOf="@id/guideline" />

2021-06-11 14:46 UTC, SEONGGYU96 requested changes
### 요약
1️⃣ MyPageFragment를 만들어서 SingleActivity의 navigation에 넣어주었습니다.
--> 네 다음에 슥 붙여봅시다. 

2️⃣ MyPage의 메인, 회원탈퇴 하위 여러뷰에서 background가 공통적으로 적용되어 layout을 따로 작성한 후 include 형식으로 만들었는데 적절한지 궁금합니다.
--> 너무 좋습니다.

3️⃣ MyPageViewModel에서 다른 user data를 받아와서 LiveData에 넣어주었는데 userName은 Two way Binding을 사용해야해서 일단 name속성만 따로 만들어주었는데 다른 좋은 방법이 있을까요?
userData에서 name을 뽑으면 타입이 LiveData이 아니라서 일단 이렇게 해두었습니다.
--> 저도 그렇게 사용합니다.

4️⃣ 기존에 만들어져있던 RoundEditText를 사용하려다 MyPage에 맞는 커스텀이 아직 아닌것 같아 일단 그냥 EditText로 만들었습니다. 그렇기 때문에 BindingAdapter를 새로 만들어주었습니다. CustomEditText의 네이밍을 조금 수정하고 My Page의 EditText의 기능을 추가할까요?? 충돌의 여지가 있어 아직 안건드렸습니다.
--> 전혀 다른 형태인점, 마이페이지 말고는 밑줄 형태의 EditText가 사용되지 않는점을 근거로 현재 하신 방법이 좋다고 생각합니다.

5️⃣ 또한 errorBody를 파싱해서 만약 서버통신에 에러가 있을 때 Toast Message로 띄워주었습니다. errorBody 파싱하는 과정을 NetworkExtension에 추가하는건 어떤가요!
--> 디자이너와 상의해봅시다! JSONObject를 사용한 방법을 몰랐는데, 확장함수에 추가하는 ㄱ ㅓ아주 아주 아주 동의합니다

5️⃣기존에 cardview로 모서리를 깎거나 동적으로 oval shape을 적용해주었었는데, Material Theme의 ShapeableImageView를 이용하면 간단하게 radius 값을 조정할 수 있습니다. 이 방법이 추천되지 않는 방법이라면 다른 방법으로 바꿔보겠슴둥
--> 기존에 ImageView를 모서리를 programmatically하게 깎던 방법에 비해서는 아주 좋은 방법 같습니다. 머터리얼은 믿음직스럽죠. 그러나  CardView를 대체할 순 없을 것 같습니다 ?

### 코멘트
리팩토링에 참고하자고 했던 프로젝트의 아키텍쳐가 잘 반영된 것 같아 너무 좋아요.
일부 수정을 요청했는데 피드백 부탁드립니다. (요청대로 수정해주셔도 되고, 이대로 두자고 설득해도 됩니다)

그리고 몇 가지 결정해야할 것들도 있네요.

1. 요청/응답 객체 이름 컨벤션 -> XXXResponse vs ResponseXXX
2. 에러 토스트를 사용자에게 보여줄 것인가?
    - YES -> request 확장함수에서 ResponseBody가 아닌 errorMessage만 반환하자!
    - NO -> request 확장함수에서 ResponseBody, errorMessage 모두 필요없다. 로그만 찍자!
3. util 패키지에 BindingAdapter.kt가 포함되는 건에 대해

2021-06-11 14:46 UTC, ethan-223 commented on app/build.gradle.kts
> +}
기존에 사용하던 dependencies 블록과 별도로 선언한 까닭이 있을까요?
그리고 각 의존성이 어디에 사용되는지 궁금합니다.

2021-06-11 14:46 UTC, ethan-223 commented on build.gradle.kts
>          jcenter()
buildSrc.java.BuildDependenciesVersion.kt 안에 코틀린 버전이 정의되어 있는데 그걸 사용하는 게 어떨까요?
```kotlin
object BuildDependenciesVersions {
    const val GRADLE = "4.1.3"
    const val GOOGLE_SERVICE = "4.3.5"
    const val KOTLIN = "1.4.32" // <- 버전 업데이트가 필요하다면 해주세요 !
    const val CORE_KTX = "1.3.2"
    ...
}
```

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/res/layout/fragment_my_page.xml
> +            tools:text="이영진"/>
RoundEditText와는 전혀 다른 형태니까 사용하지 않는 게 맞네요.
그런데 AppCompatEditText를 사용하면 어떨까요 ?

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/res/layout/fragment_my_page.xml
> +            app:layout_constraintStart_toStartOf="@id/edittext_user_name" />
AppCompatTextView!

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/res/layout/background_mypage.xml
> +            app:layout_constraintTop_toBottomOf="@+id/stormtoolbar_mypage" />
AppCompatImageView!

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
제가 알기론 EditText는 이미 양방향 데이터바인딩을 위한 장치가 마련되어있을텐데요🤔
이게 없으면 정상동작을 하지 않나요?

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +
BindingAdapter의 위치가 조금 애매하네요.
아직 결정한 것은 없지만 util보다는 다른 패키기가 좋은 것 같습니다.
1. BindingAdapter들을 모아놓을 bindingadapters 패키지 만들기
2. 추후 커스텀뷰를 모아둘 패키지("view" or "customview" etc ... )에 함께 두기
3. 기타 의견

정해볼까요 !?

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
url이 null일때에 기본 이미지를 명시적으로 적용하는 이유가 궁금합니다.
```kotlin
if (url != null) {
    Glide.with(context).load(url).into(this)
}
```
별다른 이유가 없다면 위처럼 축약할 수 있을 것 같아요. 있다면 죄삼다.

2021-06-11 14:46 UTC, ethan-223 commented on app/src/main/java/com/stormers/storm/round/fragment/HostRoundSettingFragment.kt
>          }
그냥 궁금한건데 혹시 원래대로 두면 에러가 나던가요? (날 것 같긴합니다만)

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/model/ResponseMyPage.kt
> +)
저는 요청 및 응답 객체를 XXXResponse, XXXRequest 로 이름을 맞췄는데 ResponseXXX 형태네요.
둘 중 뭐가 되어도 상관없지만 통일하면 일관성 있고 좋을 것 같아요.
뭘로 할까요 ?,? (정말 아무 상관 없음)

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/fragment/MyPageFragment.kt
> +        setToolbar()
BaseBindingFragment 에서 lifecycleOwner를 이미 지정해주고 있어서 해당 부분은 제거해도 될 것 같아요.
그런데 이제보니 BaseBindingFragment에서 viewLifecycleOwner가 아니라 this(Fragment 인스턴스의 LifecycleOwner)를 넣고 있는데 같이 수정해줄 수 있을까요 ? 제 실수네요.

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/fragment/MyPageFragment.kt
> +    }
에러를 시각적으로 사용자에게 보여줄지 말지는 디자이너와 먼저 상의해보는 게 좋을 것 같은데 어떤가요?

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +            }
아니 에러바디가 `JSONObject(error.string())` 이거 하나로 파싱이 되나요? 너무 좋네요.
제가 알고 있던 방식은 Retrofit 인스턴스를 사용하는 거였는데, 그래서 활용을 못하고 있었어요.
```kotlin
fun <T> Call<T>.request(callback: RequestCallback<T>) {
    enqueue(object: Callback<T> {
        override fun onResponse(call: Call<T>, response: Response<T>) {
            if (response.isSuccessful) {
                callback.onSuccess(response.body()!!)
                response.errorBody()
            } else {
                callback.onFailure(false, response.errorBody())
            }
        }

        override fun onFailure(call: Call<T>, t: Throwable) {
            callback.onFailure(true)
        }
    })
}

interface RequestCallback<T> {
    fun onSuccess(response: T)
    fun onFailure(isNetworkError: Boolean, errorBody: ResponseBody? = null) // <- 파라미터를 만들어두긴 했으나 쓰질 못하고 있었음
}
```
확장함수에서 에러메시지를 로그로 찍고싶었으나 Retrofit 객체를 사용해야하는줄 알고 포기했는데 .. 만약 JSONObject를 사용해서 간단히 파싱할 수 있다면 여기서 바로 활용하면 될 것 같아요 !
```kotlin
fun <T> Call<T>.request(callback: RequestCallback<T>) {
    enqueue(object: Callback<T> {
        override fun onResponse(call: Call<T>, response: Response<T>) {
            if (response.isSuccessful) {
                callback.onSuccess(response.body()!!)
                response.errorBody()
            } else {
                //확장함수 단위에서 에러 메시지 파싱
                //에러 메시지를 여기서 로그 찍어도 아주 좋을듯
                callback.onFailure(false, JSONObject(response.errorBody().error.toString()))
            }
        }

        override fun onFailure(call: Call<T>, t: Throwable) {
            callback.onFailure(true)
        }
    })
}

interface RequestCallback<T> {
    fun onSuccess(response: T)
    //콜백에서는 불필요한 데이터를 많이 포함하고 있는 ResponseBody가 아닌 관심사인 errorMessage만 파라미터로 받음
    fun onFailure(isNetworkError: Boolean, errorMessage? = null)
}
```
깃헙에서 코드 수정해본거라 동작할진 모르겠지만 이런식으로 확장함수 단위에서 에러 메시지를 파싱하면 어떨까요? 의견 주세요

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +        get() = _isSuccessFetchData
에러 발생 여부에 따라 boolean key를 지정하고 message를 할당하려고 한 것 같은데, Map 자료구조의 목적과 사뭇 달라보입니다.
별도의 객체를 만드는 게 비용이 적을듯한데, 매번 클래스를 또 정의하는 게 번거로워서 Map을 선택했을까요?

제가 생각했을때, 사실 에러가 발생하지 않았을 때에는 성공 메시지는 필요하지 않습니다.(적어도 ViewModel 단계에서는요)
즉, 에러가 발생했을 때에만 errorMessage가 필요합니다.(이마저도 토스트로 보여주지 않는다면 필요없을 수도)
우선 에러 메시지를 ViewModel에서 활용한다고 가정했을때 다음과 같은 방법이 좋을 것 같습니다.

```kotlin
private val _errorMessage = MutableLiveData<String?>(null)
val errorMessage: LiveData<String?>
    get() = _errorMessage
```
이렇게 가볍게 사용하면 어떨까요? 그리고 이렇게 정형화된 형태로 에러 메시지를 핸들링하게 되면 다음과 같은 방법도 사용할 수 있습니다.
```kotlin
//ViewModel을 확장하는 NetworkViewModel 
class NetworkViewModel: ViewModel() {
    //기본적으로 에러를 핸들링할 수 있는 LiveData를 가짐
    protected val _errorMessage = MutableLiveData<String?>(null)
    val errorMessage: LiveData<String?>
        get() = _errorMessage
    ...
}
```
이런식으로 추상화가 가능합니다. 그럼 앞으로 Network를 사용하는 모든 ViewModel은 이를 상속해서 일관된 방법으로 에러를 핸들링할 수 있겠네요!
어떻게 생각하시나요?

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +        get() = _isSuccessFetchData
일단 이 부분은 "토스트로 에러 메시지를 사용자에게 보여줄지 말지"를 결정한 다음에 의논해도 될 것 같긴합니다. 보여주지 않는다면 ViewModel에선 전혀 필요하지 않으니까요.

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +    val userName = MutableLiveData<String>()
양방향 데이터바인딩을 위해 Name을 따로 뺐다고 했죠?
저도 그렇게 하는 편입니다만, 그럼 userData도 그냥 `val userImage: LiveData<String>`으로 바꾸면 어떨까요?
MyPageModel이 가지고 있는 3개의 멤버 변수 중 image에 대한 정보밖에 사용하지 않으니까요.
이로써 MyPageViewModel은 의존객체를 1개 줄일 수 있게 됩니다 ㅎ

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
그럼 이 BindingAdapter는 둥근 모서리를 가진 CardView를 대체할 때 사용하게 되나요?
살짝 찾아보니 ShapeableImageView는 ViewGroup을 상속하지 않기 때문에 CardView를 대체할 수는 없을 것 같습니다.
ImageView의 모서리를 깎을 때는 아주 유용한 View라고 생각이 드네요 ! (기존에 programmatically하게 자르던 방법보다 훨씬 좋음)

2021-06-11 14:46 UTC, SEONGGYU96 commented on app/src/main/res/values/strings.xml
> +    <string name="withdrawal">회원 탈퇴</string>
나중에 string 리소스 쌓이면 구분이 어려울 것 같은데 앞에 "mypage_" 를 붙이는 게 어떨까요?

2021-06-12 02:05 UTC, SONPYEONGHWA commented on app/build.gradle.kts
> +}
엇 이 부분은 다시 확인해봐야겠네요... sync하면서 자동으로 추가된거 같은데 다시 한번 확인해보겠습니다.

2021-06-12 02:06 UTC, SONPYEONGHWA commented on build.gradle.kts
>          jcenter()
이 부분도 위에 dependency가 추가되면서 자동으로 된 거 같습니다. 확인해보겠습니다!

2021-06-12 02:10 UTC, SONPYEONGHWA commented on app/src/main/res/layout/fragment_my_page.xml
> +            tools:text="이영진"/>
저도 모든 컴포넌트들을 특정 테마가 필요한 것이 아니라면 AppCompat하위의 컴포넌트를 이용하는데 동의합니다!
 하위 관련된 코멘트들도 적용하겠습니다!

2021-06-12 02:14 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +        get() = _isSuccessFetchData
맞습니다!
map을 사용했던 것도 모두 UI에서 Toast 메세지를 띄워주려고 하면서 불필요한 코드가 작성이 됐네요.
리팩토링이 사실 기존 기능의 변경없이 코드의 개선을 해야하는데, 이 점을 간과했네요...
Toast를 없애고 훨씬 간단한 로직으로 처리할 수 있을 것 같습니다!

2021-06-12 02:14 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/mypage/MyPageViewModel.kt
> +    val userName = MutableLiveData<String>()
반영하겠슴둥 ㅎㅎ

2021-06-12 02:15 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
맞습니다! cardview가 아니라 단순 corner radius가 들어간 ImageView처리에 용이합니다!!!

2021-06-12 02:16 UTC, SONPYEONGHWA commented on app/src/main/res/values/strings.xml
> +    <string name="withdrawal">회원 탈퇴</string>
반영하겠습니다 ㅎㅎ

2021-06-12 02:39 UTC, SONPYEONGHWA commented
요청/응답 객체 이름 컨벤션 -> XXXResponse vs ResponseXXX

--> 이 부분은 모델들이 각 패키지 내에 속해있기 때문에 그 안에서는 Response가 앞에 붙는게 조금 더 직관적일 것 같아서 했는데, 다른 클래스들과 통일성 있게 가려면 뒤에 가는 게 맞을 수도 있겠네요!!

에러 토스트를 사용자에게 보여줄 것인가?
YES -> request 확장함수에서 ResponseBody가 아닌 errorMessage만 반환하자!
NO -> request 확장함수에서 ResponseBody, errorMessage 모두 필요없다. 로그만 찍자!

--> 기존 기능에서는 안보여주었기 때문에 리팩터링에서는 에러 토스트를 안보여주는게 맞는 것 같습니다. 로그만 찍는게 좋을 것 같아요!

util 패키지에 BindingAdapter.kt가 포함되는 건에 대해

--> BindingAdapter에서도 궁금한게 있었는데 깜빡했네요. 
기존에 view패키지가 정의되어 있으니 거기에 넣어놓겠습니다.
그리고 RoundEditTextBindingAdapter처럼 관련기능끼리 BindingAdapter를 묶어 놓는게 좋을까요??
제가 만든 BindingAdapter에는 사실 ImageView, EditText등 여러가지 컴포넌트들에 대한 함수가 섞여있습니다.
기존에 해놓은 것처럼 명확하게 따로 분리를 해놓을까요?
혹은 각 컴포넌트들에 해당하는 함수들이 1개이거나 적다면 공통적인 부분들은 하나의 클래스에 넣어놔도 될까요?

2021-06-12 04:47 UTC, SEONGGYU96 commented
> 요청/응답 객체 이름 컨벤션 -> XXXResponse vs ResponseXXX
> 
> --> 이 부분은 모델들이 각 패키지 내에 속해있기 때문에 그 안에서는 Response가 앞에 붙는게 조금 더 직관적일 것 같아서 했는데, 다른 클래스들과 통일성 있게 가려면 뒤에 가는 게 맞을 수도 있겠네요!!
> 
> 에러 토스트를 사용자에게 보여줄 것인가?
> YES -> request 확장함수에서 ResponseBody가 아닌 errorMessage만 반환하자!
> NO -> request 확장함수에서 ResponseBody, errorMessage 모두 필요없다. 로그만 찍자!
> 
> --> 기존 기능에서는 안보여주었기 때문에 리팩터링에서는 에러 토스트를 안보여주는게 맞는 것 같습니다. 로그만 찍는게 좋을 것 같아요!
> 
> util 패키지에 BindingAdapter.kt가 포함되는 건에 대해
> 
> --> BindingAdapter에서도 궁금한게 있었는데 깜빡했네요.
> 기존에 view패키지가 정의되어 있으니 거기에 넣어놓겠습니다.
> 그리고 RoundEditTextBindingAdapter처럼 관련기능끼리 BindingAdapter를 묶어 놓는게 좋을까요??
> 제가 만든 BindingAdapter에는 사실 ImageView, EditText등 여러가지 컴포넌트들에 대한 함수가 섞여있습니다.
> 기존에 해놓은 것처럼 명확하게 따로 분리를 해놓을까요?
> 혹은 각 컴포넌트들에 해당하는 함수들이 1개이거나 적다면 공통적인 부분들은 하나의 클래스에 넣어놔도 될까요?

Response가 앞에 붙는 게 더 직관적일거라고 생각이 들면 그렇게 하는게 좋겠어요. 저는 아무생각없이 뒤에 붙였던거라 조금이라도 이유 있는 선택이 옳다고 생각합니다. Login 부분에 사용된 것들만 고치면 되니까 따로 브랜치 파서 해볼게요.

BindingAdapter를 종류별로 모아두는게 경험상 편하더라구요. 그런데 말씀하신 것 처럼 해당하는 함수가 1개이거나 공통적인 부분이 있다면 모아두는 게 오히려 좋을 수 있습니다. 그리고 저는 만약 한 곳에서만 사용되고 있는 바인딩어댑터라면 그냥 Fragment에서 코드로 적용하기도 합니다.
이 부분에 대해서는 정답이 없으니 득실을 잘 따져보고 알아서 선택하면 될 것 같아요. 그런데 하나의 클래스에 모아둘거라면 뭔가 이름을 바꾸는 것도 좋을듯합니다? (ex. GeneralBindingAdapter..? 모르겠네요.. 그냥 둘까..?)

2021-06-12 05:00 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +
아 물어봤던거 여기서 답장해줬구나
ㅋㅋㅋㅋ

2021-06-12 05:27 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/mypage/fragment/MyPageFragment.kt
> +        setToolbar()
아하 BindingFragment에서 이미 지정해줬군요 ㅋㅋㅋ lifecycleOwner수정할게요!

2021-06-12 05:30 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/round/fragment/HostRoundSettingFragment.kt
>          }
아 이거 예전에 풀받고 돌려보려다 컴파일할 때 에러가 나서 바꿨었던거 같은데,,, 모르고 커밋에 올려버렸네요,,ㅠ

2021-06-12 05:31 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
별다른 이유가 없습니다,,,저렇게 쓰려다가 if문에 else 없으면 뭔가 찝찝해서 저렇게 해놨었습니다ㅋㅋㅋ

2021-06-12 05:36 UTC, SONPYEONGHWA commented on app/src/main/java/com/stormers/storm/util/BindingAdapter.kt
> +    }
`
android:text="@={data.text}"
`
  
예전에 이런식으로 EditText에 바로 Two-way Binding 적용해봤는데 에러가 나더라구요! 
구글링해봤을 때 저렇게 inversebindingadapter 지정해주어야한다고 해서 그 뒤로는 저렇게 써왔습니다!
혹시 다른 방법이 있나요???

2021-06-12 08:02 UTC, SEONGGYU96 approved these changes
고생하셨습니다 ㅎ

2021-06-12 08:05 UTC, merged